-- MySQL Script generated by MySQL Workbench
-- Sun 22 Dec 2019 10:04:11 AM PST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Example
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Example
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Example` DEFAULT CHARACTER SET utf8 ;
USE `Example` ;

-- -----------------------------------------------------
-- Table `Example`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Example`.`users` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`),
  CONSTRAINT `fk_users_1`
    FOREIGN KEY ()
    REFERENCES `Example`.`users` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Test DB for HW';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
